import React from "react";
// import testi1 from "../assets/testimonial-1.jpg";
// import testi2 from "../assets/testimonial-2.jpg";
import testi3 from "../assets/testimonial-3.jpg";
import shape1 from "../assets/bg-shape-1.svg";
import linkdin from "../assets/icon-linkedin.svg";
import ceo from '../assets/CEO.jpg'
import ceo2 from '../assets/CEO2.jpg'




export default function Testimonial() {
  return (
    <section className="testimonial-area">
      <div className="custom-container">
        <div className="testimonial-slider-wrap">
          <div className="testimonial-slider swiper">
            <div className="swiper-wrapper">
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img
                    className="animation-slide-right bg-shape"
                    src={shape1}
                    alt="Shape"
                  />
                  <span className="platform-name">
                    <img src={linkdin} alt="Icon" />
                  </span>
                  <h1>
                    Platform helped me to increase my sales and revenue
                    generated by Ooglesoft technologies
                  </h1>
                  <p>
                    One aspect that sets IT Services apart is their proactive
                    approach to security. In today's digital landscape,
                    protecting our sensitive data is of utmost importance.
                  </p>
                  <div className="author-box d-flex align-items-center">
                    <img src={ceo} alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Veer Singh</h4>
                      <p>CEO & COO</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={shape1} alt="Shape" />
                  <span className="platform-name">
                    <img src={linkdin} alt="Icon" />
                  </span>
                  <h1>
                    Celebso give the best service and top customer support.
                    Really like to have more projects with you
                  </h1>
                  <p>
                    One aspect that sets IT Services apart is their proactive
                    approach to security. In today's digital landscape,
                    protecting our sensitive data is of utmost importance.
                  </p>
                  <div className="author-box d-flex align-items-center">
                    <img src={ceo2} alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Arti Acharya</h4>
                      <p>CEO & COO</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={shape1} alt="Shape" />
                  <span className="platform-name">
                    <img src={linkdin} alt="Icon" />
                  </span>
                  <h1>
                    We’ve been using bluebase for a few years, It is very simple
                    and easy to approach team and management
                  </h1>
                  <p>
                    One aspect that sets IT Services apart is their proactive
                    approach to security. In today's digital landscape,
                    protecting our sensitive data is of utmost importance.
                  </p>
                  <div className="author-box d-flex align-items-center">
                    <img src={testi3} alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Rachel Olsem</h4>
                      <p>Full Stack Developer</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="swiper-button-prev">
            <i class="iconoir-arrow-left"></i>
          </div>
          <div className="swiper-button-next">
            <i class="iconoir-arrow-right"></i>
          </div>
        </div>
      </div>
    </section>
  );
}
