import React from "react";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import testi3 from "../assets/testimonial-3.jpg";
import test1 from '../assets/testimonial-1.jpg';
import test2 from '../assets/testimonial-2.jpg';
import shape1 from "../assets/bg-shape-1.svg";
import linkdin from "../assets/icon-linkedin.svg";

export default function Testimonialslider() {
  const settings = {
    slidesToShow: 1,
    slidesToScroll: 1,
    arrows: false,
    dots: false,
    infinite: true,
    autoplay: true,
    autoplaySpeed: 3000,
    speed: 2000, // Adjust the speed as needed
    pauseOnFocus: false,
    pauseOnHover: false,
    cssEase: 'cubic-bezier(0.25, 0.1, 0.25, 1.0)',
    // cssEase: "Linear",
    responsive: [
      {
        breakpoint: 768,
        settings: {
          slidesToShow: 1,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
        },
      },
    ],
  };
  return (
    <section className="testimonial-area">
      <div className="custom-container">
        <div className="testimonial-slider-wrap">
          <div className="testimonial-slider swiper">
            <Slider {...settings}>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img
                    className="animation-slide-right bg-shape"
                    src={shape1}
                    alt="Shape"
                  />
                  <span className="platform-name">
                    <img src={linkdin} alt="Icon" />
                  </span>
                  <h1>
                  Platform helped me to increase my sales and revenue
                  generated by bluebase technologies.
                  </h1>
                  <p>
                  One aspect that sets IT Services apart is their proactive
                  approach to security. In today's digital landscape,
                  protecting our sensitive data is of utmost importance.
                  </p>
                  <div className="author-box d-flex align-items-center">
                    <img src={test1} alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Serana Belluci</h4>
                      <p>Product Designer</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={shape1} alt="Shape" />
                  <span className="platform-name">
                    <img src={linkdin} alt="Icon" />
                  </span>
                  <h1>
                  Bluebase give the best service and top customer
                  support. Really like to have more projects with you.
                  </h1>
                  <p>
                  One aspect that sets IT Services apart is their proactive 
                  approach to security. In today's digital landscape, 
                  protecting our sensitive data is of utmost importance.
                  </p>
                  <div className="author-box d-flex align-items-center">
                    <img src={test2} alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Megan Clarke</h4>
                      <p>CEO, Sanlab</p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="swiper-slide testimonial-item">
                <div className="testimonial-item-body">
                  <img className="bg-shape" src={shape1} alt="Shape" />
                  <span className="platform-name">
                    <img src={linkdin} alt="Icon" />
                  </span>
                  <h1>
                  We have been using bluebase for a few years, It is very simple
                  and easy to approach team and management.
                  </h1>
                  <p>
                  One aspect that sets IT Services apart is their proactive
                  approach to security. In today's digital landscape,
                  protecting our sensitive data is of utmost importance.
                  </p>
                  <div className="author-box d-flex align-items-center">
                    <img src={testi3} alt="Testimonial" />
                    <div className="author-box-content">
                      <h4>Rachel Olsem</h4>
                      <p>Full Stack Developer</p>
                    </div>
                  </div>
                </div>
              </div>
            </Slider>
          </div>
        </div>
      </div>
    </section>

  )
}
